apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-absa-deploy
  namespace: sumit
spec:
  schedule: "*/1 * * * *"       
  concurrencyPolicy: "Forbid"  
  startingDeadlineSeconds: 200  
  suspend: false                
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            parent: "cronjob-absa-deploy"
        spec:
          containers:
          - name: cronjob-absa-deploy
            image: image-registry.openshift-image-registry.svc:5000/sumit/absademo
            #command: ["java", "-jar", "/opt/app/configenvironment.jar", "hello", "these", "are", "from", "args"]
            #command: ["java", "-jar", "/opt/app/configenvironment.jar"]
            env: 
              - name: client.name
                valueFrom:
                  configMapKeyRef:
                    name: absa-config-deploy
                    key: client.name 
              - name: client.project
                valueFrom:
                  configMapKeyRef:
                    name: absa-config-deploy
                    key: client.project
              - name: client.status
                valueFrom:
                  configMapKeyRef:
                    name: absa-config-deploy
                    key: client.status 
          restartPolicy: OnFailure
